//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zombicide.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zombicide.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à node
        ///49
        ///
        ///link
        ///0 7
        ///1 8
        ///2 9
        ///3 10
        ///4 11
        ///5 12
        ///6 13
        ///7 0 14
        ///8 1 15 14
        ///9 2 16
        ///10 3 17
        ///11 4 18
        ///12 5 29 20
        ///13 6 20
        ///14 7 21 8
        ///15 8 22
        ///16 9 23 17
        ///17 16 18 10
        ///18 17 11 25
        ///19 12 26
        ///20 13 27 12
        ///21 14 28
        ///22 15 29
        ///23 16 30
        ///24 31
        ///25 16 32
        ///26 19 33
        ///27 20 34
        ///28 21 35 29
        ///29 28 30 22 36
        ///30 29 23 31
        ///31 30 32 24 39
        ///32 31 25 33
        ///33 32 34 26 40
        ///34 27 33 41
        ///35 28 42
        ///36 37 43 29
        ///37 36 43 38
        ///38 37 39 44
        ///39 38 44 45 40 31
        ///40 41 46 47 33
        ///41 34 48
        ///42 35
        ///43 36 37 44
        ///44 43 38 39 45
        ///45 44 39 46 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string map1 {
            get {
                return ResourceManager.GetString("map1", resourceCulture);
            }
        }
    }
}
