//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zombicide.Assets {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zombicide.Assets.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de personnage(s) par joueur.
        /// </summary>
        public static string CHARACTER_NUMBER_BY_PLAYER {
            get {
                return ResourceManager.GetString("CHARACTER_NUMBER_BY_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages.
        /// </summary>
        public static string CHARACTERS {
            get {
                return ResourceManager.GetString("CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnalisé.
        /// </summary>
        public static string CUSTOMIZED_GAME {
            get {
                return ResourceManager.GetString("CUSTOMIZED_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulté.
        /// </summary>
        public static string DIFFICULTY {
            get {
                return ResourceManager.GetString("DIFFICULTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facile.
        /// </summary>
        public static string DIFFICULTY_EASY {
            get {
                return ResourceManager.GetString("DIFFICULTY_EASY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficile.
        /// </summary>
        public static string DIFFICULTY_HARD {
            get {
                return ResourceManager.GetString("DIFFICULTY_HARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cauchemar.
        /// </summary>
        public static string DIFFICULTY_NIGHTMARE {
            get {
                return ResourceManager.GetString("DIFFICULTY_NIGHTMARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moyen.
        /// </summary>
        public static string DIFFICULTY_NORMAL {
            get {
                return ResourceManager.GetString("DIFFICULTY_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue..
        /// </summary>
        public static string EXCEPTION_AN_ERROR_OCCURED {
            get {
                return ResourceManager.GetString("EXCEPTION_AN_ERROR_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string EXCEPTION_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brouillard de guerre.
        /// </summary>
        public static string FOG_OF_WAR_MODE {
            get {
                return ResourceManager.GetString("FOG_OF_WAR_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour.
        /// </summary>
        public static string FOG_OF_WAR_MODE_DAY {
            get {
                return ResourceManager.GetString("FOG_OF_WAR_MODE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de restriction sur le champ de vision..
        /// </summary>
        public static string FOG_OF_WAR_MODE_DAY_TOOLTIP {
            get {
                return ResourceManager.GetString("FOG_OF_WAR_MODE_DAY_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nuit.
        /// </summary>
        public static string FOG_OF_WAR_MODE_NIGHT {
            get {
                return ResourceManager.GetString("FOG_OF_WAR_MODE_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ de vision est limité à 2 cases. N&apos;avancez pas trop vite ni tout seul !.
        /// </summary>
        public static string FOG_OF_WAR_MODE_NIGHT_TOOLTIP {
            get {
                return ResourceManager.GetString("FOG_OF_WAR_MODE_NIGHT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seuls les zombies se trouvant dans le champ de vision des personnages sont visibles sur le plateau. Attention lorsque vous tournez au coin d&apos;une rue !.
        /// </summary>
        public static string FOG_OF_WAR_MODE_TOOLTIP {
            get {
                return ResourceManager.GetString("FOG_OF_WAR_MODE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode de jeu.
        /// </summary>
        public static string GAME_MODE {
            get {
                return ResourceManager.GetString("GAME_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charger partie.
        /// </summary>
        public static string LOAD_GAME {
            get {
                return ResourceManager.GetString("LOAD_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle partie.
        /// </summary>
        public static string NEW_GAME {
            get {
                return ResourceManager.GetString("NEW_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OPTIONS.
        /// </summary>
        public static string OPTION_TITLE {
            get {
                return ResourceManager.GetString("OPTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de joueur(s).
        /// </summary>
        public static string PLAYER_NUMBER {
            get {
                return ResourceManager.GetString("PLAYER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueurs.
        /// </summary>
        public static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de quitter l&apos;application.
        ///Souhaitez-vous continuer ?.
        /// </summary>
        public static string QUIT_CONFIRM_QUESTION {
            get {
                return ResourceManager.GetString("QUIT_CONFIRM_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string QUIT_GAME {
            get {
                return ResourceManager.GetString("QUIT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string QUIT_TITLE {
            get {
                return ResourceManager.GetString("QUIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard.
        /// </summary>
        public static string STANDARD_GAME {
            get {
                return ResourceManager.GetString("STANDARD_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode furtif.
        /// </summary>
        public static string STEALTH_MODE {
            get {
                return ResourceManager.GetString("STEALTH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A chaque action bruyante, des zombies arrivent des cotés du plateau !.
        /// </summary>
        public static string STEALTH_MODE_TOOLTIP {
            get {
                return ResourceManager.GetString("STEALTH_MODE_TOOLTIP", resourceCulture);
            }
        }
    }
}
